import { PostcodeLocation } from '../../types/postcode';

/**
 * Pre-seeded landmark dataset, verified against the official NDAPS API across
 * Nigeria. Used for instant exploration and the "Surprise me" action.
 *
 * This lives client-side so the app can be deployed as a static bundle with no
 * server dependency.
 */
export const NIGERIA_DISCOVERY_POINTS: PostcodeLocation[] = [
  {
    postcode: 'FC-02-D43-LG-01',
    display: 'FC 02 D43 LG 01',
    name: 'The Infrastructure Bank PLC',
    category: 'Commercial & Financial',
    state: 'FC',
    stateName: 'Federal Capital Territory',
    lga: '02',
    lgaName: 'Abuja Municipal Area Council',
    district: 'D43',
    area: 'LG',
    unit: '01',
    lat: 9.057977,
    lng: 7.493727,
    address: 'Central Business District, Abuja FCT',
    buildingUse: 'non-residential',
  },
  {
    postcode: 'LA-11-A12-AK-08',
    display: 'LA 11 A12 AK 08',
    name: '14, Ipodo Street',
    category: 'Residential',
    state: 'LA',
    stateName: 'Lagos',
    lga: '11',
    lgaName: 'Ikeja',
    district: 'A12',
    area: 'AK',
    unit: '08',
    lat: 6.596577,
    lng: 3.342144,
    address: '14, Ipodo Street, Ikeja, Lagos',
    buildingUse: 'residential',
  },
  {
    postcode: 'LA-08-A12-EE-01',
    display: 'LA 08 A12 EE 01',
    name: '0062 Adeola Odeku Street',
    category: 'Commercial Hub',
    state: 'LA',
    stateName: 'Lagos',
    lga: '08',
    lgaName: 'Eti-Osa',
    district: 'A12',
    area: 'EE',
    unit: '01',
    lat: 6.428235,
    lng: 3.422026,
    address: '0062 Adeola Odeku Street, Victoria Island, Lagos',
    buildingUse: 'residential',
  },
  {
    postcode: 'OY-26-B60-BH-10',
    display: 'OY 26 B60 BH 10',
    name: 'No 3 Adeyemi Layout',
    category: 'Residential',
    state: 'OY',
    stateName: 'Oyo',
    lga: '26',
    lgaName: 'Ona Ara',
    district: 'B60',
    area: 'BH',
    unit: '10',
    lat: 7.377651,
    lng: 3.947044,
    address: 'No 3 Adeyemi Layout, Ogbere Idi Osan, Ibadan',
    buildingUse: 'residential',
  },
  {
    postcode: 'KN-31-A08-FJ-33',
    display: 'KN 31 A08 FJ 33',
    name: 'Idris Ahmad House',
    category: 'Residential Complex',
    state: 'KN',
    stateName: 'Kano',
    lga: '31',
    lgaName: 'Nasarawa',
    district: 'A08',
    area: 'FJ',
    unit: '33',
    lat: 12.002151,
    lng: 8.591997,
    address: 'Raudakeyi Hotoron Arewa, Nasarawa, Kano',
    buildingUse: 'residential',
  },
  {
    postcode: 'RI-15-A34-BM-03',
    display: 'RI 15 A34 BM 03',
    name: 'Winsco Serves Limited',
    category: 'Industrial / Commercial',
    state: 'RI',
    stateName: 'Rivers',
    lga: '15',
    lgaName: 'Obio/Akpor',
    district: 'A34',
    area: 'BM',
    unit: '03',
    lat: 4.815101,
    lng: 7.050161,
    address: 'Woji Community, Obio-Akpo LGA, Port Harcourt, Rivers',
    buildingUse: 'residential',
  },
];