import { StateGeoInfo } from '../../types/postcode';

export const NIGERIA_CENTER: [number, number] = [9.082, 8.6753];
export const NIGERIA_DEFAULT_ZOOM = 6;

// Comprehensive accurate coordinates for all 37 Nigerian States and FCT
export const NIGERIA_STATES: Record<string, StateGeoInfo> = {
  AB: {
    code: 'AB',
    name: 'Abia',
    capital: 'Umuahia',
    zone: 'South East',
    center: [5.4527, 7.5248],
    zoom: 9,
    lgaCount: 17,
  },
  AD: {
    code: 'AD',
    name: 'Adamawa',
    capital: 'Yola',
    zone: 'North East',
    center: [9.3265, 12.3984],
    zoom: 8,
    lgaCount: 21,
  },
  AK: {
    code: 'AK',
    name: 'Akwa Ibom',
    capital: 'Uyo',
    zone: 'South South',
    center: [5.0377, 7.9128],
    zoom: 9,
    lgaCount: 31,
  },
  AN: {
    code: 'AN',
    name: 'Anambra',
    capital: 'Awka',
    zone: 'South East',
    center: [6.2209, 7.07],
    zoom: 9,
    lgaCount: 21,
  },
  BA: {
    code: 'BA',
    name: 'Bauchi',
    capital: 'Bauchi',
    zone: 'North East',
    center: [10.3159, 9.8442],
    zoom: 8,
    lgaCount: 20,
  },
  BE: {
    code: 'BE',
    name: 'Benue',
    capital: 'Makurdi',
    zone: 'North Central',
    center: [7.332, 8.741],
    zoom: 8,
    lgaCount: 23,
  },
  BR: {
    code: 'BR',
    name: 'Borno',
    capital: 'Maiduguri',
    zone: 'North East',
    center: [11.8333, 13.15],
    zoom: 8,
    lgaCount: 27,
  },
  BY: {
    code: 'BY',
    name: 'Bayelsa',
    capital: 'Yenagoa',
    zone: 'South South',
    center: [4.7719, 6.0699],
    zoom: 9,
    lgaCount: 8,
  },
  CR: {
    code: 'CR',
    name: 'Cross River',
    capital: 'Calabar',
    zone: 'South South',
    center: [5.8702, 8.5988],
    zoom: 8,
    lgaCount: 18,
  },
  DE: {
    code: 'DE',
    name: 'Delta',
    capital: 'Asaba',
    zone: 'South South',
    center: [5.6805, 5.9685],
    zoom: 8,
    lgaCount: 25,
  },
  EB: {
    code: 'EB',
    name: 'Ebonyi',
    capital: 'Abakaliki',
    zone: 'South East',
    center: [6.3249, 8.1137],
    zoom: 9,
    lgaCount: 13,
  },
  ED: {
    code: 'ED',
    name: 'Edo',
    capital: 'Benin City',
    zone: 'South South',
    center: [6.5438, 5.8987],
    zoom: 8,
    lgaCount: 18,
  },
  EK: {
    code: 'EK',
    name: 'Ekiti',
    capital: 'Ado-Ekiti',
    zone: 'South West',
    center: [7.6333, 5.2333],
    zoom: 9,
    lgaCount: 16,
  },
  EN: {
    code: 'EN',
    name: 'Enugu',
    capital: 'Enugu',
    zone: 'South East',
    center: [6.4584, 7.5464],
    zoom: 9,
    lgaCount: 17,
  },
  FC: {
    code: 'FC',
    name: 'Federal Capital Territory',
    capital: 'Abuja',
    zone: 'North Central',
    center: [9.0579, 7.4951],
    zoom: 10,
    lgaCount: 6,
  },
  GM: {
    code: 'GM',
    name: 'Gombe',
    capital: 'Gombe',
    zone: 'North East',
    center: [10.2897, 11.1673],
    zoom: 8,
    lgaCount: 11,
  },
  IM: {
    code: 'IM',
    name: 'Imo',
    capital: 'Owerri',
    zone: 'South East',
    center: [5.4836, 7.0332],
    zoom: 9,
    lgaCount: 27,
  },
  JI: {
    code: 'JI',
    name: 'Jigawa',
    capital: 'Dutse',
    zone: 'North West',
    center: [12.228, 9.5616],
    zoom: 8,
    lgaCount: 27,
  },
  KD: {
    code: 'KD',
    name: 'Kaduna',
    capital: 'Kaduna',
    zone: 'North West',
    center: [10.5105, 7.4165],
    zoom: 8,
    lgaCount: 23,
  },
  KE: {
    code: 'KE',
    name: 'Kebbi',
    capital: 'Birnin Kebbi',
    zone: 'North West',
    center: [11.4584, 4.1999],
    zoom: 8,
    lgaCount: 21,
  },
  KG: {
    code: 'KG',
    name: 'Kogi',
    capital: 'Lokoja',
    zone: 'North Central',
    center: [7.7337, 6.6906],
    zoom: 8,
    lgaCount: 21,
  },
  KN: {
    code: 'KN',
    name: 'Kano',
    capital: 'Kano',
    zone: 'North West',
    center: [12.0022, 8.592],
    zoom: 8,
    lgaCount: 44,
  },
  KT: {
    code: 'KT',
    name: 'Katsina',
    capital: 'Katsina',
    zone: 'North West',
    center: [12.9855, 7.6171],
    zoom: 8,
    lgaCount: 34,
  },
  KW: {
    code: 'KW',
    name: 'Kwara',
    capital: 'Ilorin',
    zone: 'North Central',
    center: [8.4799, 4.5418],
    zoom: 8,
    lgaCount: 16,
  },
  LA: {
    code: 'LA',
    name: 'Lagos',
    capital: 'Ikeja',
    zone: 'South West',
    center: [6.5244, 3.3792],
    zoom: 10,
    lgaCount: 20,
  },
  NA: {
    code: 'NA',
    name: 'Nasarawa',
    capital: 'Lafia',
    zone: 'North Central',
    center: [8.4932, 8.5153],
    zoom: 8,
    lgaCount: 13,
  },
  NI: {
    code: 'NI',
    name: 'Niger',
    capital: 'Minna',
    zone: 'North Central',
    center: [9.9309, 5.5983],
    zoom: 8,
    lgaCount: 25,
  },
  OG: {
    code: 'OG',
    name: 'Ogun',
    capital: 'Abeokuta',
    zone: 'South West',
    center: [7.1475, 3.3619],
    zoom: 9,
    lgaCount: 20,
  },
  ON: {
    code: 'ON',
    name: 'Ondo',
    capital: 'Akure',
    zone: 'South West',
    center: [7.2571, 5.2058],
    zoom: 9,
    lgaCount: 18,
  },
  OS: {
    code: 'OS',
    name: 'Osun',
    capital: 'Osogbo',
    zone: 'South West',
    center: [7.5629, 4.52],
    zoom: 9,
    lgaCount: 30,
  },
  OY: {
    code: 'OY',
    name: 'Oyo',
    capital: 'Ibadan',
    zone: 'South West',
    center: [7.8537, 3.9312],
    zoom: 8,
    lgaCount: 33,
  },
  PL: {
    code: 'PL',
    name: 'Plateau',
    capital: 'Jos',
    zone: 'North Central',
    center: [9.2182, 9.5179],
    zoom: 8,
    lgaCount: 17,
  },
  RI: {
    code: 'RI',
    name: 'Rivers',
    capital: 'Port Harcourt',
    zone: 'South South',
    center: [4.8156, 7.0498],
    zoom: 9,
    lgaCount: 23,
  },
  SK: {
    code: 'SK',
    name: 'Sokoto',
    capital: 'Sokoto',
    zone: 'North West',
    center: [13.0609, 5.2476],
    zoom: 8,
    lgaCount: 23,
  },
  TA: {
    code: 'TA',
    name: 'Taraba',
    capital: 'Jalingo',
    zone: 'North East',
    center: [8.8937, 11.36],
    zoom: 8,
    lgaCount: 16,
  },
  YB: {
    code: 'YB',
    name: 'Yobe',
    capital: 'Damaturu',
    zone: 'North East',
    center: [12.0, 11.5],
    zoom: 8,
    lgaCount: 17,
  },
  ZA: {
    code: 'ZA',
    name: 'Zamfara',
    capital: 'Gusau',
    zone: 'North West',
    center: [12.1628, 6.6613],
    zoom: 8,
    lgaCount: 14,
  },
};
